### ISSUE TITLE
Fail to search npm-asset/estree-walker

### ISSUE THREAD

**Issue by neronmoon** [hiqdev/asset-packagist#19]
I got 500 in console for update query. Here is trace

```
Exception 'Fxp\Composer\AssetPlugin\Exception\InvalidCreateRepositoryException' with message 'The "repository.url" parameter of "estree-walker" npm asset package must be present for create a VCS Repository
If the config comes from the NPM Registry, override the config with a custom Asset VCS Repository' 

in /home/sol/prj/hiqdev/asset-packagist.org/vendor/fxp/composer-asset-plugin/Repository/NpmRepository.php:154

Stack trace:
#0 /home/sol/prj/hiqdev/asset-packagist.org/vendor/fxp/composer-asset-plugin/Repository/NpmRepository.php(76): Fxp\Composer\AssetPlugin\Repository\NpmRepository->getVcsRepositoryUrl(Array, 'estree-walker')
#1 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/registry/RegistryTrait.php(38): Fxp\Composer\AssetPlugin\Repository\NpmRepository->createVcsRepositoryConfig(Array, 'estree-walker')
#2 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/models/AssetPackage.php(203): hiqdev\assetpackagist\registry\NpmRegistry->buildVcsRepository('estree-walker')
#3 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/controllers/SiteController.php(99): hiqdev\assetpackagist\models\AssetPackage->update()
#4 [internal function]: hiqdev\assetpackagist\controllers\SiteController->actionUpdate()
#5 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#7 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('update', Array)
#8 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('site/update', Array)
#9 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /home/sol/prj/hiqdev/asset-packagist.org/web/index.php(8): yii\base\Application->run()
#11 {main}
```

**Comment by SilverFire** [comment]
Package is currently available: https://asset-packagist.org/package/search?query=npm-asset%2Festree-walker
